import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:ruhh/core/data/models/transaction_local.dart';
import 'package:ruhh/core/theme/nb_colors.dart';
import 'package:ruhh/core/theme/ruhh_tokens.dart';
import 'package:ruhh/features/budget/ledger/budget_inr.dart';

String ledgerRowTitle(TransactionLocal tx) {
  if (tx.title.isNotEmpty) return tx.title;
  if (tx.ledgerType == BudgetLedgerType.salary) return 'Salary';
  return tx.category.isNotEmpty ? tx.category : tx.ledgerType.name;
}

String ledgerRowSubtitle(TransactionLocal tx) {
  if (tx.isAutoGenerated && tx.ledgerType == BudgetLedgerType.salary) {
    return 'Auto · ${DateFormat.yMMMd().format(tx.occurredAt)}';
  }
  if (tx.note.isNotEmpty) return tx.note;
  return DateFormat.yMMMd().format(tx.occurredAt);
}

Color ledgerAmountColor(TransactionLocal tx) {
  if (tx.ledgerType == BudgetLedgerType.expense) {
    return NBMetrics.expenseRed;
  }
  return NBMetrics.incomeGreen;
}

class LedgerListRow extends StatelessWidget {
  const LedgerListRow({
    super.key,
    required this.tx,
    this.onTap,
    this.showSign = true,
  });

  final TransactionLocal tx;
  final VoidCallback? onTap;
  final bool showSign;

  @override
  Widget build(BuildContext context) {
    final t = context.ruhh;
    final theme = Theme.of(context).textTheme;
    final amountColor = ledgerAmountColor(tx);
    final isDebit = tx.ledgerType == BudgetLedgerType.expense;
    final signed = isDebit ? -tx.amount : tx.amount;
    final amountText = showSign
        ? BudgetInr.formatSigned(signed)
        : BudgetInr.format(tx.amount);
    final typeLabel = tx.ledgerType.name;

    return Material(
      color: Colors.transparent,
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(t.radiusCardMedium),
        child: Ink(
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(t.radiusCardMedium),
            border: Border.all(color: t.divider),
            color: t.surfacePrimary,
          ),
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Container(
                  width: 4,
                  height: 48,
                  decoration: BoxDecoration(
                    color: amountColor,
                    borderRadius: BorderRadius.circular(2),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        ledgerRowTitle(tx),
                        style: theme.titleMedium?.copyWith(
                          color: t.textPrimary,
                          fontWeight: FontWeight.w600,
                        ),
                        maxLines: 2,
                        overflow: TextOverflow.ellipsis,
                      ),
                      const SizedBox(height: 4),
                      Text.rich(
                        TextSpan(
                          children: [
                            TextSpan(
                              text: typeLabel,
                              style: theme.bodySmall?.copyWith(
                                color: amountColor,
                                fontWeight: FontWeight.w700,
                              ),
                            ),
                            TextSpan(
                              text: ' · ${ledgerRowSubtitle(tx)}',
                              style: t.caption(theme).copyWith(
                                    color: t.textSecondary,
                                  ),
                            ),
                          ],
                        ),
                        maxLines: 2,
                        overflow: TextOverflow.ellipsis,
                      ),
                    ],
                  ),
                ),
                const SizedBox(width: 12),
                ConstrainedBox(
                  constraints: const BoxConstraints(minWidth: 88),
                  child: Text(
                    amountText,
                    textAlign: TextAlign.right,
                    style: theme.titleMedium?.copyWith(
                      fontWeight: FontWeight.w800,
                      fontSize: 17,
                      color: amountColor,
                      letterSpacing: -0.2,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class LedgerIncomeTotalCard extends StatelessWidget {
  const LedgerIncomeTotalCard({super.key, required this.total});

  final double total;

  @override
  Widget build(BuildContext context) {
    final t = context.ruhh;
    final theme = Theme.of(context).textTheme;
    const green = NBMetrics.incomeGreen;
    return Container(
      width: double.infinity,
      padding: EdgeInsets.all(t.spaceCardPadding),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(t.radiusCardLarge),
        border: Border.all(color: green, width: 1.5),
        color: t.surfacePrimary,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('Total income', style: t.caption(theme)),
          const SizedBox(height: 6),
          Text(
            BudgetInr.format(total),
            style: theme.headlineMedium?.copyWith(
              color: green,
              fontWeight: FontWeight.w800,
            ),
          ),
        ],
      ),
    );
  }
}
