import 'package:ruhh/core/data/models/transaction_local.dart';

String budgetMonthKey(DateTime date) {
  final y = date.year;
  final m = date.month.toString().padLeft(2, '0');
  return '$y-$m';
}

DateTime budgetMonthStart(String monthKey) {
  final parts = monthKey.split('-');
  return DateTime(int.parse(parts[0]), int.parse(parts[1]));
}

String? budgetPreviousMonthKey(String monthKey) {
  final start = budgetMonthStart(monthKey);
  final prev = DateTime(start.year, start.month - 1);
  return budgetMonthKey(prev);
}

/// First day of month for auto salary entries.
DateTime budgetMonthFirstDay(String monthKey) => budgetMonthStart(monthKey);

/// Normalize legacy rows into ledger fields.
void budgetNormalizeTransaction(TransactionLocal t) {
  if (t.monthKey.isEmpty) {
    t.monthKey = budgetMonthKey(t.occurredAt);
  }
  if (t.categoryRemoteId.isEmpty) {
    t.categoryRemoteId = t.category;
  }
  if (t.ledgerType == BudgetLedgerType.expense && t.isIncome) {
    if (t.isAutoGenerated ||
        t.category == 'Salary' ||
        t.title.toLowerCase().contains('salary')) {
      t.ledgerType = BudgetLedgerType.salary;
    } else {
      t.ledgerType = BudgetLedgerType.credit;
    }
  } else if (!t.isIncome && t.ledgerType != BudgetLedgerType.expense) {
    t.ledgerType = BudgetLedgerType.expense;
  }
  t.isIncome = t.ledgerType != BudgetLedgerType.expense;
}

bool budgetTransactionInLedger(TransactionLocal t) {
  if (t.scheduleType != BudgetScheduleType.normal && !t.paid) {
    return false;
  }
  return true;
}
