import 'package:ruhh/core/data/models/transaction_local.dart';
import 'package:ruhh/features/budget/ledger/budget_category_ids.dart';
import 'package:ruhh/features/budget/ledger/budget_month_key.dart';

/// Section 5 — auto monthly salary transaction.
abstract final class BudgetSalaryEngine {
  static bool hasSalaryForMonth(
    List<TransactionLocal> txs,
    String monthKey,
  ) {
    for (final t in txs) {
      budgetNormalizeTransaction(t);
      if (t.monthKey == monthKey &&
          t.ledgerType == BudgetLedgerType.salary &&
          budgetTransactionInLedger(t)) {
        return true;
      }
    }
    return false;
  }

  static TransactionLocal buildAutoSalary({
    required String userId,
    required String remoteId,
    required double amount,
    required String monthKey,
    required String walletName,
  }) {
    final date = budgetMonthFirstDay(monthKey);
    return TransactionLocal()
      ..remoteId = remoteId
      ..userId = userId
      ..amount = amount
      ..ledgerType = BudgetLedgerType.salary
      ..isIncome = true
      ..title = 'Monthly salary'
      ..category = 'Salary'
      ..categoryRemoteId = BudgetCategoryIds.salary
      ..account = walletName
      ..note = ''
      ..occurredAt = date
      ..monthKey = monthKey
      ..isAutoGenerated = true
      ..scheduleType = BudgetScheduleType.normal
      ..paid = true
      ..recurrence = 'none';
  }
}
