import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:ruhh/core/data/models/budget_extras_local.dart';
import 'package:ruhh/core/data/models/transaction_local.dart';
import 'package:ruhh/core/theme/nb_colors.dart';
import 'package:ruhh/core/widgets/nb_button.dart';
import 'package:ruhh/core/widgets/nb_dialog.dart';
import 'package:ruhh/core/widgets/nb_layout.dart';
import 'package:ruhh/core/widgets/nb_scaffold.dart';
import 'package:ruhh/core/widgets/nb_text_field.dart';
import 'package:ruhh/core/services/budget_notification_alerts.dart';
import 'package:ruhh/core/services/notification_service.dart';
import 'package:ruhh/features/budget/budget_repository.dart';
import 'package:ruhh/features/settings/settings_controller.dart';
import 'package:ruhh/features/budget/ledger/budget_inr.dart';
import 'package:ruhh/features/budget/widgets/category_display.dart';

/// Section 7.2 — Expense / Credit only (salary is automatic).
class AddTransactionPage extends ConsumerStatefulWidget {
  const AddTransactionPage({super.key, this.transactionId});

  final int? transactionId;

  @override
  ConsumerState<AddTransactionPage> createState() => _AddTransactionPageState();
}

class _AddTransactionPageState extends ConsumerState<AddTransactionPage> {
  BudgetLedgerType _type = BudgetLedgerType.expense;
  final _amountCtrl = TextEditingController();
  final _noteCtrl = TextEditingController();
  DateTime _date = DateTime.now();
  CategoryLocal? _category;
  TransactionLocal? _existing;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    if (widget.transactionId == null) return;
    final repo = await ref.read(budgetRepositoryProvider.future);
    final tx = await repo.getTransaction(widget.transactionId!);
    if (tx == null || !mounted) return;
    final cats = await repo.categories();
    CategoryLocal? cat;
    if (tx.categoryRemoteId.isNotEmpty) {
      for (final c in cats) {
        if (c.remoteId == tx.categoryRemoteId) {
          cat = c;
          break;
        }
      }
    }
    cat ??= () {
      for (final c in cats) {
        if (c.name == tx.category) return c;
      }
      return null;
    }();
    if (!mounted) return;
    setState(() {
      _existing = tx;
      _category = cat;
      _type = tx.ledgerType == BudgetLedgerType.salary
          ? BudgetLedgerType.salary
          : tx.ledgerType;
      _amountCtrl.text = tx.amount.toStringAsFixed(0);
      _noteCtrl.text = tx.note;
      _date = tx.occurredAt;
    });
  }

  @override
  void dispose() {
    _amountCtrl.dispose();
    _noteCtrl.dispose();
    super.dispose();
  }

  Future<void> _save(BudgetRepository repo) async {
    final amount = BudgetInr.parse(_amountCtrl.text);
    if (amount == null || amount <= 0 || _category == null) return;

    if (_existing != null) {
      await repo.upsertLedgerTransaction(
        id: _existing!.id,
        type: _type,
        amount: amount,
        category: _category!,
        note: _noteCtrl.text.trim(),
        date: _date,
        isAutoGenerated: _existing!.isAutoGenerated,
      );
    } else {
      await repo.upsertLedgerTransaction(
        type: _type,
        amount: amount,
        category: _category!,
        note: _noteCtrl.text.trim(),
        date: _date,
      );
    }
    bumpBudgetRefresh(ref);
    if (_type == BudgetLedgerType.expense && _category != null) {
      final n = await ref.read(notificationServiceProvider.future);
      final settings = ref.read(settingsControllerProvider);
      await BudgetNotificationAlerts(n, settings, repo).evaluateAfterExpense(
        categoryName: _category!.name,
        month: _date,
      );
    }
    if (mounted) context.pop();
  }

  @override
  Widget build(BuildContext context) {
    final repoAsync = ref.watch(budgetRepositoryProvider);
    final incomeMode = _type == BudgetLedgerType.credit ||
        _type == BudgetLedgerType.salary;
    return repoAsync.when(
      data: (repo) => FutureBuilder(
        future: repo.activeCategories(income: incomeMode),
        builder: (context, snap) {
          final cats = snap.data ?? [];
          if (_category == null && cats.isNotEmpty) {
            _category = cats.first;
          }
          if (_category != null &&
              !cats.any((c) => c.remoteId == _category!.remoteId)) {
            _category = cats.isNotEmpty ? cats.first : null;
          }

          return NBModuleScaffold(
            title: _existing == null ? 'Add transaction' : 'Edit transaction',
            body: NBPageBody(
              child: ListView(
                children: [
                  if (_existing?.ledgerType == BudgetLedgerType.salary)
                    const NBEmptyState(
                      message:
                          'Editing this month\'s auto salary. Changing amount only affects this month.',
                    )
                  else
                    Row(
                      children: [
                        NBChip(
                          label: 'Expense',
                          selected: _type == BudgetLedgerType.expense,
                          onTap: () => setState(() {
                            _type = BudgetLedgerType.expense;
                            _category = null;
                          }),
                        ),
                        const SizedBox(width: 8),
                        NBChip(
                          label: 'Credit',
                          selected: _type == BudgetLedgerType.credit,
                          color: NBMetrics.incomeGreen,
                          onTap: () => setState(() {
                            _type = BudgetLedgerType.credit;
                            _category = null;
                          }),
                        ),
                      ],
                    ),
                  const SizedBox(height: 16),
                  NBTextField(
                    controller: _amountCtrl,
                    label: 'Amount (₹)',
                    keyboardType:
                        const TextInputType.numberWithOptions(decimal: true),
                  ),
                  const SizedBox(height: 12),
                  Text('Category',
                      style: Theme.of(context).textTheme.titleMedium),
                  const SizedBox(height: 8),
                  CategoryEmojiChipRow(
                    categories: cats,
                    selectedRemoteId: _category?.remoteId,
                    onSelected: (c) => setState(() => _category = c),
                  ),
                  const SizedBox(height: 12),
                  NBTextField(controller: _noteCtrl, label: 'Note (optional)'),
                  const SizedBox(height: 12),
                  ListTile(
                    contentPadding: EdgeInsets.zero,
                    title: const Text('Date'),
                    subtitle: Text(
                      '${_date.year}-${_date.month.toString().padLeft(2, '0')}-${_date.day.toString().padLeft(2, '0')}',
                    ),
                    trailing: const Icon(Icons.calendar_today_outlined),
                    onTap: () async {
                      final picked = await showDatePicker(
                        context: context,
                        initialDate: _date,
                        firstDate: DateTime(2000),
                        lastDate: DateTime(2100),
                      );
                      if (picked != null) setState(() => _date = picked);
                    },
                  ),
                  const SizedBox(height: 16),
                  NBButton(
                    label: 'Save',
                    color: NBMetrics.incomeGreen,
                    onPressed: cats.isEmpty ? null : () => _save(repo),
                  ),
                  if (_existing != null) ...[
                    const SizedBox(height: 8),
                    NBButton(
                      label: 'Delete',
                      color: NBMetrics.expenseRed,
                      onPressed: () async {
                        final ok = await showNBConfirmDialog(
                          context: context,
                          title: 'Delete transaction?',
                          message: 'This will be removed on all synced devices.',
                          confirmLabel: 'Delete',
                        );
                        if (ok != true || !context.mounted) return;
                        await repo.deleteLedgerTransaction(_existing!.id);
                        bumpBudgetRefresh(ref);
                        if (context.mounted) context.pop();
                      },
                    ),
                  ],
                ],
              ),
            ),
          );
        },
      ),
      loading: () => const NBModuleScaffold(
        title: 'Transaction',
        body: Center(child: CircularProgressIndicator()),
      ),
      error: (e, _) =>
          NBModuleScaffold(title: 'Transaction', body: Text('$e')),
    );
  }
}
